language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --dev --prefer-dist -o
  - echo $MANDRILL_API_KEY > .env

script:
  - ./vendor/bin/phpunit
